apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: new-nginx
    type: canary  # add this
  name: new-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: new-nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: new-nginx
        type: canary  # add this
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        resources: {}
        volumeMounts:
          # mountPath: /usr/share/nginx/html/index.html  # this runs in a error
          - mountPath: /usr/share/nginx/html/
            name: canary-vol
      volumes:
      - name: canary-vol
        configMap:
          name: canary
status: {}
