apiVersion: v1
kind: Namespace
metadata:
  name: secret-and-consuming-as-env-variables
spec: {}
status: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret
  namespace: secret-and-consuming-as-env-variables
data:
  Key3: VEcxTVNHSlphSE5uVjFwM1RtbG1hWEZoVW05eVNEaFU=
type: Opaque
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: secret-and-consuming-as-env-variables
spec:
  containers:
  - image: nginx
    name: nginx
  restartPolicy: Never