apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: add-sa-to-deployment
spec: {}
status: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: deploy-sa
  namespace: add-sa-to-deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
  namespace: add-sa-to-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.14.0
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}

