apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: add-securitycontext-to-pod
spec: {}
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  name: non-root
  namespace: add-securitycontext-to-pod
spec:
  securityContext:   # add
    runAsUser: 1000  # add
    runAsGroup: 3000 # add
    fsGroup: 2000    # add
  volumes:
  - name: sec-ctx-vol
    emptyDir: {}
  containers:
  - image: busybox:1.28
    name: secured-container
    command: [ "sh", "-c", "sleep 1h" ]
    volumeMounts:
    - name: sec-ctx-vol
      mountPath: /data/demo
    securityContext: # add
      allowPrivilegeEscalation: false # add
