apiVersion: v1
kind: Namespace
metadata:
  name: sidecar-pattern
spec: {}
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  name: sidecar-pod
  namespace: sidecar-pattern
  labels:
    app: sidecar-pattern
spec:
  volumes:
  - name: logs
    emptyDir: {}

  containers:
  - name: app
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "while true; do date >> /var/log/date.txt; sleep 10;done"]
    volumeMounts:
    - name: logs
      mountPath: /var/log

  - name: sidecar
    image: centos/httpd
    ports:
    - containerPort: 80
    volumeMounts:
    - name: logs
      mountPath: /var/www/html
