apiVersion: v1
kind: Namespace
metadata:
  name: multi-container-pods
spec: {}
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: multi-container
  name: multi-container
  namespace: multi-container-pods
spec:
  containers:
  - name: busybox
    image: busybox
    command:
    - sleep
    - "3600"
  - name: nginx
    image: nginx
