apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: mycronjob
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: mycronjob
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - command:
            - echo
            - greetings from your cluster
            image: busybox
            name: mycronjob
            resources: {}
          restartPolicy: OnFailure
  schedule: '*/1 * * * *'
status: {}
